### ISSUE TITLE
fig2dev command not found

### ISSUE THREAD

**Issue by dinatale2** [opensfs/lustre-buildbot-config#1]
Starting to see this on our CentOS build slaves. I believe that means we need to have xfig and transfig packages installed as dependencies. I remember reading somewhere that docutils is also not required anymore. Is that true?

**Comment by nosuchthing** [comment]
For master, python-docutils is no longer required. See [LU-7841](https://jira.hpdd.intel.com/browse/LU-7841)
http://review.whamcloud.com/#/c/18792/

I was unaware that xfig or transfig were requirements. When I cscope the source I'm not finding the string fig2dev anywhere.

**Comment by nosuchthing** [comment]
Ok, I do see it in the build.hpdd.intel.com output for the latest master build. Maybe has something to do with inkernel ofed doc?

make[3]: Entering directory `/var/lib/jenkins/workspace/lustre-master/arch/x86_64/build_type/server/distro/el7/ib_stack/inkernel/lnet/doc'
fig2dev -L eps file.fig > file.eps
fig2dev -L eps flow_new.fig > flow_new.eps
fig2dev -L eps get.fig > get.eps
fig2dev -L eps mpi.fig > mpi.eps
fig2dev -L eps portals.fig > portals.eps
fig2dev -L eps put.fig > put.eps
make[3]: Leaving directory`/var/lib/jenkins/workspace/lustre-master/arch/x86_64/build_type/server/distro/el7/ib_stack/inkernel/lnet/doc'

https://build.hpdd.intel.com/job/lustre-master/arch=x86_64,build_type=server,distro=el7,ib_stack=inkernel/lastBuild/consoleText

**Comment by morrone** [comment]
cscope tends to only parse and index C-related files.  You'll want to use something like "git grep" for everything else:

$ git grep fig2dev
lnet/doc/Makefile.am:`   -fig2dev -L eps $< > $@

It has been there for almost 13 years. :)  I imagine that we just started noticing that warning in the build logs, not that the warnings just started recently.
