### ISSUE TITLE
Install libkeyutils in all ABIs

### ISSUE THREAD

**Issue by morrone** [opensfs/lustre-buildbot-config#10]
We should install libkeyutils in all of the ABIs so the gss support can be built:

> checking for keyctl_search in -lkeyutils... no
> configure: WARNING:
> 
> libkeyutils is not found, which is required by gss keyring backend
> 
> configure: WARNING:
> 
> Cannot enable gss keyring. See above for details.

**Comment by dinatale2** [comment]
libkeyutils will also be added to bb-dependencies.sh for slaves that require bootstrapping.

I also believe you mean AMIs instead of ABIs.

**Comment by dinatale2** [comment]
I installed keyutils on CentOS 6 and 7, but the package does not provide keyctl_search. The keyutils package does however provide keyctl. Am I installing the wrong package?

**Comment by morrone** [comment]
Is keyctl a command, and keyctl_search a function?  Is the actual
libkeyutils library installed?  And if it is, is the development package
with the requisite headers installed?

Chris

**Comment by dinatale2** [comment]
Ah, there's keyutils-lib and keyutils-lib-devel. Not what I anticipated the names to be. That solved it.

**Comment by dinatale2** [comment]
Opened a pull request that solves this. (#16)
