### ISSUE TITLE
Need to reduce cloning bandwidth demands

### ISSUE THREAD

**Issue by morrone** [opensfs/lustre-buildbot-config#12]
We need to reduce our git clone bandwidth demands on gerrit.  We're probably pulling down 1.7GB for every single change right now, and that is really excessive.  It also slows the build, and you know how I like the builds to be fast. :)

Off the top of my head I see two possibilities:

1) Make a custom buildbot source step to do a shallow clone (--depth 200 or so should be sufficient for the versioning code)
2) Have a new Builder that does nothing but clone changes from gerrit, and generate the tarball for use by the other Builders that actually compile and package Lustre.

I am leaning toward option 2.

If the build slave for the new tarball Builder is long-lived, then we can use standard buildbot capabilities.  We can probably use buildbot.steps.source.git.Gerrit's "method=fresh".  Since the node is long-lived, the fetch of the specific change will be fast, any tiny.  There is no need to try to make the initial clone shallow.

The work to capture the build products would be a prerequisite of option 2.

**Comment by dinatale2** [comment]
Some notes on how this will be implemented. We will introduce a new builder that will simply clone the change from Gerrit. Then call autogen, configure --enable-dist, and make dist. And from there, the tarball will be uploaded to the buildbot master and stored for download by the other builders. Finally, the new builder will trigger all the other builders to start building.

I'm not sure how properties work with triggered builds. I'm going to need to test that.

The tarball can be stored in the public_html folder of the build master, this should allow others to download the tarball. This would end up satisfying a portion of the publish build products goal.
