### ISSUE TITLE
Implement static known environment for build slaves

### ISSUE THREAD

**Issue by morrone** [opensfs/lustre-buildbot-config#3]
The current build farm configuration dynamically installs random unknown versions of Lustre build requirements every time an EC2 build slave is instantiated.  We need to stop doing that.

This is currently breaking the Lustre build on the SUSE builder.  There was likely a new SUSE kernel released recently.  That newer kernel is now being pulled in as part of the kernel-devel installation (amongst other packages).  The installed kernel-devel code and the running kernel no longer match, and that breaks the Lustre build on SUSE.

Having a randomly changing build environment is not going to be acceptable for the main Lustre builders.  We need to have a known static, reproducible environment for each builder type.

One possible way to achieve this would be to have custom AMIs for each builder with the Lustre build requirements preinstalled.

**Comment by dinatale2** [comment]
AMIs for each builder will have the necessary kernel development headers installed that match the kernel version. Basically, any package that depends on the kernel version should be pre-installed. These will become our base AMIs per distribution. If those need to be refreshed every once and a while, that is fine.

From there, we can explore other options. But, I prefer all the non-kernel dependent packages to be installed once a slave spins up. This will allow us to weed out if new dependencies have been added. If we find that the dependencies need to be cleaned up later on, so be it. From a maintainability perspective, this is much more manageable as well. And, we will always be building with the newest version of packages this way.

**Comment by morrone** [comment]
> But, I prefer all the non-kernel dependent packages to be installed once a slave spins up. This will allow us to weed out if new dependencies have been added.

That doesn't let us weed out dependencies and differently than if we had them installed in the AMI.  

Assuming we don't find a better method than custom AMIs, all of the prerequisites packages need to be installed in the AMI, not just the kernel.

> And, we will always be building with the newest version of packages this way.

But our requirement is exactly the opposite.  We want a reliable, repeatable build process for the main builders.  That means a static build environment of known packages.  Package versions should only change in those main builders when we make the the explicit decision to do so.  Likely we would introduce _new_ builders for each new major build change, retiring older builders as we see fit.

So, overruled.  Find a way to make the entire environment of the builder static, and common on all slaves of a given builder.

**Comment by dinatale2** [comment]
I will start working on AMIs for this. I plan to remove the install dependencies portion of the build process for existing builders. I will worry about if we should build ZFS separately since some distros don't have repos containing the devel packages/headers.

**Comment by morrone** [comment]
From my point of view, ZFS is a lustre dependency too.  Why should it be considered separately?  The question of static install in the AMI vs dynamic install at boot time seems like a somewhat orthogonal topic to whether or not a distro has prebuilt packages.
