### ISSUE TITLE
Install kabi-whitelist package in CentOS builder AMIs

### ISSUE THREAD

**Issue by morrone** [opensfs/lustre-buildbot-config#8]
We should try installing the kabi-whitelist package in the CentOS builder ABIs, per this find-requires warning:

> Finding  Requires: /usr/lib/rpm/redhat/find-requires
> ---
> 
> **********************\* KERNEL ABI COMPATIBILITY WARNING ***********************
> ---
> 
> The kernel ABI reference files (provided by kabi-whitelists) were not found.
> No compatibility check was performed. Please install the kABI reference files
> and rebuild if you would like to verify compatibility with kernel ABI.

It might be good to make sure that Lustre still build with kabi-whitelists installed though.  It could be that lustre is using something that it shouldn't at the moment, and that might break all builds.  If so, then we should open a Lustre ticket and work on obeying the whitelists.

**Comment by dinatale2** [comment]
I'm going to add kabi-whitelist as a dependency in bb-dependencies.sh for CentOS and RHEL.

**Comment by morrone** [comment]
And update the ABIs?

**Comment by dinatale2** [comment]
Do you mean AMIs? Yes, the AMIs will be updated.

**Comment by morrone** [comment]
Yes, AMIs.

**Comment by dinatale2** [comment]
Just to confirm, the package is kernel-abi-whitelists correct?

**Comment by morrone** [comment]
It sounds like it, but I don't know for certain.

**Comment by dinatale2** [comment]
Opened a pull request that solves this. (#16)
