### ISSUE TITLE
--without-ldiskfs should be --disable-ldiskfs

### ISSUE THREAD

**Issue by morrone** [opensfs/lustre-buildbot-config#9]
In some of the buildbot config scripts, the lustre configure option "--without-ldiskfs" is used.  That should be updated to the current "--disable-ldiskfs" option.

**Comment by dinatale2** [comment]
Are you talking about bb-build-lustre-pkg.sh? Is bb-build-lustre-srpm.sh going to have to change as well?

**Comment by morrone** [comment]
I didn't look at the scripts; I just see the commands that are being run through the logs in the buildbot interface.  If you have a question about how the configure script works let me know.
